@HanyFokVan.Api_HostAddress = http://localhost:5286

### Get current weather
GET {{HanyFokVan.Api_HostAddress}}/weather/current
Accept: application/json

### Get nearby stations
# @prompt lat
# @prompt lon
GET {{HanyFokVan.Api_HostAddress}}/weather/nearby-stations?lat=46.30&lon=25.30
Accept: application/json

###
